<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Yathish-PC" failures="1" tests="1" name="Default test(failed)(failed)" time="0.106" errors="0" timestamp="31 Oct 2018 11:31:23 GMT">
  <testcase classname="Test.TestNGRetryFailed" name="test3" time="0.031">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at Test.TestNGRetryFailed.test3(TestNGRetryFailed.java:26)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="Test.TestNGRetryFailed" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="Test.TestNGRetryFailed" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Default test(failed)(failed) -->
